# Global shared values for staging
global:
  # Add global variables here if needed

backend:
  extraEnvs:
    - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
      value: "http://keycloak.keycloak.svc.cluster.local/realms/Yas"
    - name: PGSSLMODE
      value: "disable"
  livenessProbe:
    initialDelaySeconds: 120
    failureThreshold: 30
  readinessProbe:
    initialDelaySeconds: 120
    failureThreshold: 30


