apiVersion: v1
data:
  gateway-routes-config.yaml: |
    spring:
      cloud:
        gateway:
          server:
            webflux:
              routes:
              - filters:
                - RewritePath=/api/(?<segment>.*), /$\{segment}
                - TokenRelay=
                id: product_api
                predicates:
                - Path=/api/product/**
                uri: http://product
              - filters:
                - RewritePath=/api/(?<segment>.*), /$\{segment}
                - TokenRelay=
                id: location_api
                predicates:
                - Path=/api/location/**
                uri: http://location
              - filters:
                - RewritePath=/api/(?<segment>.*), /$\{segment}
                - TokenRelay=
                id: inventory_api
                predicates:
                - Path=/api/inventory/**
                uri: http://inventory
              - filters:
                - RewritePath=/api/(?<segment>.*), /$\{segment}
                - TokenRelay=
                id: cart_api
                predicates:
                - Path=/api/cart/**
                uri: http://cart
              - filters:
                - RewritePath=/api/(?<segment>.*), /$\{segment}
                - TokenRelay=
                id: customer_api
                predicates:
                - Path=/api/customer/**
                uri: http://customer
              - filters:
                - RewritePath=/api/(?<segment>.*), /$\{segment}
                - TokenRelay=
                id: media_api
                predicates:
                - Path=/api/media/**
                uri: http://media
              - filters:
                - RewritePath=/api/(?<segment>.*), /$\{segment}
                - TokenRelay=
                id: rating_api
                predicates:
                - Path=/api/rating/**
                uri: http://rating
              - filters:
                - RewritePath=/api/(?<segment>.*), /$\{segment}
                - TokenRelay=
                id: tax_api
                predicates:
                - Path=/api/tax/**
                uri: http://tax
              - filters:
                - RewritePath=/api/(?<segment>.*), /$\{segment}
                - TokenRelay=
                id: promotion_api
                predicates:
                - Path=/api/promotion/**
                uri: http://protion
              - filters:
                - RewritePath=/api/(?<segment>.*), /$\{segment}
                - TokenRelay=
                id: search_api
                predicates:
                - Path=/api/search/**
                uri: http://search
              - filters:
                - RewritePath=/api/(?<segment>.*), /$\{segment}
                - TokenRelay=
                id: order_api
                predicates:
                - Path=/api/order/**
                uri: http://order
              - filters:
                - RewritePath=/api/(?<segment>.*), /$\{segment}
                - TokenRelay=
                id: recommendation_api
                predicates:
                - Path=/api/recommendation/**
                uri: http://recommendation
              - filters:
                - RewritePath=/api/(?<segment>.*), /$\{segment}
                - TokenRelay=
                id: webhook_api
                predicates:
                - Path=/api/webhook/**
                uri: http://webhook
              - filters:
                - RewritePath=/api/(?<segment>.*), /$\{segment}
                - TokenRelay=
                id: sampledata_api
                predicates:
                - Path=/api/sampledata/**
                uri: http://sampledata
              - filters:
                - RewritePath=/api/(?<segment>.*), /$\{segment}
                - TokenRelay=
                id: payment_api
                predicates:
                - Path=/api/payment/**
                uri: http://payment
              - filters:
                - RewritePath=/api/(?<segment>.*), /$\{segment}
                - TokenRelay=
                id: payment-paypal_api
                predicates:
                - Path=/api/payment-paypal/**
                uri: http://payment-paypal
              - id: ui
                predicates:
                - Path=/**
                uri: ${UI_HOST}
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: dev-yas-configuration:/ConfigMap:dev/yas-gateway-routes-config-configmap
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"gateway-routes-config.yaml":"spring:\n  cloud:\n    gateway:\n      server:\n        webflux:\n          routes:\n          - filters:\n            - RewritePath=/api/(?\u003csegment\u003e.*), /$\\{segment}\n            - TokenRelay=\n            id: product_api\n            predicates:\n            - Path=/api/product/**\n            uri: http://product\n          - filters:\n            - RewritePath=/api/(?\u003csegment\u003e.*), /$\\{segment}\n            - TokenRelay=\n            id: location_api\n            predicates:\n            - Path=/api/location/**\n            uri: http://location\n          - filters:\n            - RewritePath=/api/(?\u003csegment\u003e.*), /$\\{segment}\n            - TokenRelay=\n            id: inventory_api\n            predicates:\n            - Path=/api/inventory/**\n            uri: http://inventory\n          - filters:\n            - RewritePath=/api/(?\u003csegment\u003e.*), /$\\{segment}\n            - TokenRelay=\n            id: cart_api\n            predicates:\n            - Path=/api/cart/**\n            uri: http://cart\n          - filters:\n            - RewritePath=/api/(?\u003csegment\u003e.*), /$\\{segment}\n            - TokenRelay=\n            id: customer_api\n            predicates:\n            - Path=/api/customer/**\n            uri: http://customer\n          - filters:\n            - RewritePath=/api/(?\u003csegment\u003e.*), /$\\{segment}\n            - TokenRelay=\n            id: media_api\n            predicates:\n            - Path=/api/media/**\n            uri: http://media\n          - filters:\n            - RewritePath=/api/(?\u003csegment\u003e.*), /$\\{segment}\n            - TokenRelay=\n            id: rating_api\n            predicates:\n            - Path=/api/rating/**\n            uri: http://rating\n          - filters:\n            - RewritePath=/api/(?\u003csegment\u003e.*), /$\\{segment}\n            - TokenRelay=\n            id: tax_api\n            predicates:\n            - Path=/api/tax/**\n            uri: http://tax\n          - filters:\n            - RewritePath=/api/(?\u003csegment\u003e.*), /$\\{segment}\n            - TokenRelay=\n            id: promotion_api\n            predicates:\n            - Path=/api/promotion/**\n            uri: http://protion\n          - filters:\n            - RewritePath=/api/(?\u003csegment\u003e.*), /$\\{segment}\n            - TokenRelay=\n            id: search_api\n            predicates:\n            - Path=/api/search/**\n            uri: http://search\n          - filters:\n            - RewritePath=/api/(?\u003csegment\u003e.*), /$\\{segment}\n            - TokenRelay=\n            id: order_api\n            predicates:\n            - Path=/api/order/**\n            uri: http://order\n          - filters:\n            - RewritePath=/api/(?\u003csegment\u003e.*), /$\\{segment}\n            - TokenRelay=\n            id: recommendation_api\n            predicates:\n            - Path=/api/recommendation/**\n            uri: http://recommendation\n          - filters:\n            - RewritePath=/api/(?\u003csegment\u003e.*), /$\\{segment}\n            - TokenRelay=\n            id: webhook_api\n            predicates:\n            - Path=/api/webhook/**\n            uri: http://webhook\n          - filters:\n            - RewritePath=/api/(?\u003csegment\u003e.*), /$\\{segment}\n            - TokenRelay=\n            id: sampledata_api\n            predicates:\n            - Path=/api/sampledata/**\n            uri: http://sampledata\n          - id: ui\n            predicates:\n            - Path=/**\n            uri: ${UI_HOST}\n"},"kind":"ConfigMap","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"dev-yas-configuration:/ConfigMap:dev/yas-gateway-routes-config-configmap","reloader.stakater.com/match":"true"},"name":"yas-gateway-routes-config-configmap","namespace":"dev"}}
    reloader.stakater.com/match: "true"
  creationTimestamp: "2026-06-25T08:31:52Z"
  name: yas-gateway-routes-config-configmap
  namespace: dev
  resourceVersion: "1314435"
  uid: 43b49ca8-d2c7-4a78-8d33-7ceb88ac733f
