apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: yas-instrumentation
  namespace: dev
spec:
  exporter:
    endpoint: http://opentelemetry-collector.{{ .Release.Namespace }}:4318
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_always_on
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
