# Cấu hình values cho môi trường Staging

# ----------------------------------------------------
# Cách override Docker Registry & Image Tags của nhóm:
# Nếu nhóm bạn dùng Docker Hub (ví dụ: minhthangzxc):
# Bạn có thể uncomment và cập nhật các dòng tương ứng dưới đây:
#
# cart:
#   backend:
#     image:
#       repository: minhthangzxc/yas-cart
#       tag: v1.2.3  # Staging thường dùng version tag cụ thể thay vì latest
# ----------------------------------------------------

# override cấu hình chung cho swagger-ui (nếu cần)
swagger-ui:
  ingress:
    enabled: true
    host: staging-api.yas.local.com
    hosts:
      - host: staging-api.yas.local.com
        paths:
          - path: /swagger-ui
            pathType: ImplementationSpecific

# Cấu hình cụ thể cho từng microservice nếu có khác biệt
yas-configuration:
  # Cấu hình credential cho môi trường Staging
  credentials:
    postgresql:
      username: yasadminuser
      password: admin_staging
    elasticsearch:
      username: yas
      password: LarUmB3A49NTg9YmgW4=
    keycloak:
      backofficeBffClientSecret: TVacLC0cQ8tiiEKiTVerTb2YvwQ1TRJF
      storefrontBffClientSecret: ZrU9I0q2uXBglBnmvyJdkl1lf0ncr8tn
      customerManagementClientSecret: NKAr3rnjwm9jlakgKpelukZGFaHYqIWE
    redis:
      password: redis_staging
    openai:
      apiKey: update-me-staging
