apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: yas-instrumentation
  namespace: dev
spec:
  exporter:
    endpoint: http://opentelemetry-collector.observability.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_always_on
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
