apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-images-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi # Dung lượng 500MB là đủ cho các ảnh mẫu
