# Global shared values for dev
global:
  # Add global variables here if needed

backend:
  extraEnvs:
    - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
      value: "http://identity.yas.local.com/realms/Yas"
    - name: PGSSLMODE
      value: "disable"
  livenessProbe:
    initialDelaySeconds: 120
    failureThreshold: 30
  readinessProbe:
    initialDelaySeconds: 120
    failureThreshold: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0        # không tạo pod mới thêm
      maxUnavailable: 1  # cho phép 1 pod down khi update

